// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvbobbonmwccytcjhacm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2Ym9iYm9ubXdjY3l0Y2poYWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTEwNTAsImV4cCI6MjA2ODA4NzA1MH0.Yp0Nl4-ojWJE_4wlEznCgGhxriDsLMQcSWJA-aAzmrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});